name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "news"
database_id = "310f6f1b-9273-4d92-9422-da38dfc1b657"
